services:
  vdel:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${IMAGE:-ghcr.io/<owner>/vdel:latest}
    container_name: vdel
    ports:
      - "8081:8080"
      - "8888:8888"
    environment:
      - VNC_PASSWORD=${VNC_PASSWORD:-vibe}
      - CODE_SERVER_PASSWORD=${CODE_SERVER_PASSWORD:-vibe}
    volumes:
      - vdel_home:/home/developer/workspace
      - vdel_codeserver:/home/developer/.local/share/code-server

  desktop:
    image: ghcr.io/linuxserver/webtop:ubuntu-xfce
    container_name: vdel-desktop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - vdel_desktop:/config
      - vdel_home:/config/workspace
    ports:
      - "8080:3000"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:3000 >/dev/null || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 20s

  code:
    image: codercom/code-server:latest
    container_name: vdel-code
    environment:
      - PASSWORD=${CODE_SERVER_PASSWORD:-vibe}
    volumes:
      - vdel_home:/home/coder/project
      - vdel_codeserver:/home/coder/.local/share/code-server
    ports:
      - "8443:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8080/healthz >/dev/null || curl -fsS http://127.0.0.1:8080 >/dev/null || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 20s

volumes:
  vdel_home:
  vdel_codeserver:
  vdel_desktop:
