version: "3.9"

services:
  vdel:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${IMAGE:-ghcr.io/<owner>/vdel:latest}
    container_name: vdel
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O- http://127.0.0.1:8080 >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s

